repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
        exclude: '\.zshrc$'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        exclude: 'envs/.*'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ["-d", "{extends: relaxed, rules: {line-length: disable}}"]

  - repo: local
    hooks:
      - id: check-frontend
        name: Check Frontend (ESLint + Prettier)
        entry: bash -c "cd apps/web-app && npm run lint && npx prettier --check ."
        language: system
        files: ^apps/web-app/.*\.([tj]sx?)$

      - id: check-backend
        name: Check Backend (Spotless Java)
        entry: bash -c "cd apps/portfolio-api-java && ./gradlew spotlessCheck"
        language: system
        files: ^apps/portfolio-api-java/.*\.java$
