events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Basic Security Headers
    server_tokens off;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    upstream webapp {
        server web-app:3000;
    }

    upstream api {
        server portfolio-api-java:8080;
    }

    server {
        listen 80;
        server_name diegosantos.me www.diegosantos.me;

        # Rota de validação do Let's Encrypt (Webroot plugin)
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Descomentar/Ajustar quando o Certbot estiver rodando
        # listen 443 ssl;
        # ssl_certificate /etc/letsencrypt/live/diegosantos.me/fullchain.pem;
        # ssl_certificate_key /etc/letsencrypt/live/diegosantos.me/privkey.pem;

        # Frontend Next.js
        location / {
            proxy_pass http://webapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Backend Java Spring Boot
        location /api/ {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Ocultar o actuator externalmente por segurança, a não ser que venha da rede interna
        location /api/actuator/ {
            # Somente IPs seguros (ex: prometheus)
            allow 172.16.0.0/12;
            allow 127.0.0.1;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            deny all;
            proxy_pass http://api/actuator/;
        }
    }
}
