version: '3.8'

# Base docker-compose.yml
# Define TODOS os serviços, redes e binds inter-containers, sem amarrar
# ao ambiente (volumes locais ou imagens finais de prod).

services:
  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    networks:
      - app-net
    depends_on:
      - web-app
      - portfolio-api-java

  postgres:
    image: postgres:16-alpine
    container_name: portfolio_postgres
    networks:
      - app-net

  web-app:
    container_name: portfolio_web_app
    networks:
      - app-net

  portfolio-api-java:
    container_name: portfolio_api_java
    networks:
      - app-net
    depends_on:
      - postgres

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
