INSERT INTO learning_events (
    external_id,
    repository_name,
    repository_url,
    pull_request_number,
    pull_request_url,
    title,
    summary,
    technical_category,
    event_date,
    status,
    is_auto_published,
    raw_source_reference,
    processed_at,
    published_at
)
SELECT
    seed.external_id,
    seed.repository_name,
    seed.repository_url,
    seed.pull_request_number,
    seed.pull_request_url,
    seed.title,
    seed.summary,
    seed.technical_category,
    seed.event_date,
    seed.status,
    seed.is_auto_published,
    seed.raw_source_reference,
    seed.processed_at,
    seed.published_at
FROM (
    VALUES
        (
            'manual-journal-20260405-01',
            'diegosantos-ai/nexo360-new',
            'https://github.com/diegosantos-ai/nexo360-new',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Arquitetura modular só faz sentido quando reduz acoplamento de verdade',
            'No Nexo 360, aprendi que separar domínio, entrada e saída não é só uma escolha estética. Essa organização reduz impacto de mudança, melhora testabilidade e facilita evoluir partes do sistema sem espalhar regra de negócio por toda a aplicação.',
            'architecture',
            TIMESTAMP '2026-04-05 10:30:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-05 10:30:00',
            TIMESTAMP '2026-04-05 10:30:00'
        ),
        (
            'manual-journal-20260405-02',
            'diegosantos-ai/nexo360-new',
            'https://github.com/diegosantos-ai/nexo360-new',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Multi-tenant exige contexto explícito, não suposição implícita',
            'Trabalhar com uma arquitetura multi-tenant reforçou uma lição importante: contexto de tenant precisa entrar no desenho do sistema desde o início. Quando isso não fica explícito em contratos, persistência e fluxo de execução, o risco de inconsistência cresce rápido.',
            'backend',
            TIMESTAMP '2026-04-05 09:15:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-05 09:15:00',
            TIMESTAMP '2026-04-05 09:15:00'
        ),
        (
            'manual-journal-20260404-01',
            'diegosantos-ai/dev-workspace',
            'https://github.com/diegosantos-ai/dev-workspace',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Ambiente reproduzível economiza mais tempo do que qualquer ajuste manual',
            'No DevOps Workspace, ficou claro que padronizar setup e automação de ambiente reduz atrito operacional, acelera onboarding e evita o custo invisível de cada máquina funcionar de um jeito. Reprodutibilidade não é detalhe; é base para trabalhar com previsibilidade.',
            'devops',
            TIMESTAMP '2026-04-04 17:40:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-04 17:40:00',
            TIMESTAMP '2026-04-04 17:40:00'
        ),
        (
            'manual-journal-20260404-02',
            'diegosantos-ai/projeto-02-terraform-cloud',
            'https://github.com/diegosantos-ai/projeto-02-terraform-cloud',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Infraestrutura como código começa a gerar valor quando vira rotina segura',
            'No projeto de infraestrutura em AWS, o aprendizado principal foi que Terraform entrega muito mais valor quando deixa de ser experimento e passa a organizar ambiente com consistência, versionamento e menor dependência de ação manual. O ganho real está na previsibilidade da operação.',
            'infrastructure',
            TIMESTAMP '2026-04-04 14:20:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-04 14:20:00',
            TIMESTAMP '2026-04-04 14:20:00'
        ),
        (
            'manual-journal-20260403-01',
            'diegosantos-ai/chat-bot-pref',
            'https://github.com/diegosantos-ai/chat-bot-pref',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'IA em produção precisa de governança antes de precisar de sofisticação',
            'Com o Munio, aprendi que aplicar IA em contexto institucional não é só integrar modelo e resposta. É garantir contexto correto, trilha de auditoria, validação de entrada e saída e uma base observável para operar com responsabilidade em ambientes mais sensíveis.',
            'ai-governance',
            TIMESTAMP '2026-04-03 16:10:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-03 16:10:00',
            TIMESTAMP '2026-04-03 16:10:00'
        ),
        (
            'manual-journal-20260403-02',
            'diegosantos-ai/chat-bot-pref',
            'https://github.com/diegosantos-ai/chat-bot-pref',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'RAG só melhora a resposta quando o contexto está realmente sob controle',
            'Ao estruturar o fluxo de RAG no Munio, a principal lição foi que recuperação de contexto não resolve sozinha o problema da qualidade. Sem isolamento adequado, política clara e contexto bem delimitado, o sistema continua vulnerável a respostas genéricas ou inconsistentes.',
            'rag',
            TIMESTAMP '2026-04-03 11:00:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-03 11:00:00',
            TIMESTAMP '2026-04-03 11:00:00'
        ),
        (
            'manual-journal-20260402-01',
            'diegosantos-ai/projeto-03-observabilidade',
            'https://github.com/diegosantos-ai/projeto-03-observabilidade',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Sem sinal operacional, troubleshooting vira tentativa e erro',
            'Na stack de observabilidade, reforcei uma aprendizagem central: logs, métricas e dashboards não servem apenas para monitorar. Eles encurtam diagnóstico, ajudam a localizar falhas com menos atrito e transformam operação reativa em leitura mais clara do sistema.',
            'observability',
            TIMESTAMP '2026-04-02 15:25:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-02 15:25:00',
            TIMESTAMP '2026-04-02 15:25:00'
        ),
        (
            'manual-journal-20260401-01',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Apresentar projeto bem também é uma competência de engenharia',
            'Ao transformar o portfólio em aplicação estruturada, com backend, conteúdo versionado e casos mais bem narrados, aprendi que comunicar arquitetura, decisão técnica e valor operacional faz parte do trabalho. Projeto bom mal explicado perde força; projeto bem comunicado vira evidência.',
            'engineering',
            TIMESTAMP '2026-04-01 18:05:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-01 18:05:00',
            TIMESTAMP '2026-04-01 18:05:00'
        )
) AS seed (
    external_id,
    repository_name,
    repository_url,
    pull_request_number,
    pull_request_url,
    title,
    summary,
    technical_category,
    event_date,
    status,
    is_auto_published,
    raw_source_reference,
    processed_at,
    published_at
)
WHERE NOT EXISTS (
    SELECT 1
    FROM learning_events existing
    WHERE existing.external_id = seed.external_id
);
