INSERT INTO learning_events (
    external_id,
    repository_name,
    repository_url,
    pull_request_number,
    pull_request_url,
    title,
    summary,
    technical_category,
    event_date,
    status,
    is_auto_published,
    raw_source_reference,
    processed_at,
    published_at
)
SELECT
    seed.external_id,
    seed.repository_name,
    seed.repository_url,
    seed.pull_request_number,
    seed.pull_request_url,
    seed.title,
    seed.summary,
    seed.technical_category,
    seed.event_date,
    seed.status,
    seed.is_auto_published,
    seed.raw_source_reference,
    seed.processed_at,
    seed.published_at
FROM (
    VALUES
        (
            'manual-journal-20260405-01',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Corrigi um 502 no deploy com healthchecks e ordem de subida',
            'Reestruturei a ordem de inicialização entre Nginx, web-app, API e Postgres para evitar upstream indisponível. Também adicionei healthchecks e validação pós-deploy para transformar erro silencioso em feedback operacional claro.',
            'ci-cd',
            TIMESTAMP '2026-04-05 10:30:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-05 10:30:00',
            TIMESTAMP '2026-04-05 10:30:00'
        ),
        (
            'manual-journal-20260405-02',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Transformei os cases em conteúdo versionado e navegável no front',
            'Organizei os projetos em Markdown com listagem, rota individual e tratamento mais editorial da leitura. O objetivo foi fazer os estudos de caso parecerem evidência de engenharia, e não catálogo de ferramentas.',
            'frontend',
            TIMESTAMP '2026-04-05 09:15:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-05 09:15:00',
            TIMESTAMP '2026-04-05 09:15:00'
        ),
        (
            'manual-journal-20260404-01',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Adicionei seed inicial dos projetos via Flyway',
            'Criei uma migration para popular a tabela de projetos a partir do conteúdo versionado do repositório. Isso reduz dependência de carga manual e melhora a previsibilidade do ambiente em produção.',
            'database',
            TIMESTAMP '2026-04-04 17:40:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-04 17:40:00',
            TIMESTAMP '2026-04-04 17:40:00'
        ),
        (
            'manual-journal-20260404-02',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Refatorei a identidade visual do portfólio para um tom editorial técnico',
            'Migrei o site de uma estética escura e pesada para uma linguagem mais clara, madura e legível. A refatoração priorizou estrutura, contraste, ritmo visual e uma sensação mais humana sem perder autoridade técnica.',
            'frontend',
            TIMESTAMP '2026-04-04 14:20:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-04 14:20:00',
            TIMESTAMP '2026-04-04 14:20:00'
        ),
        (
            'manual-journal-20260403-01',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Troquei diagramas pouco legíveis por assets visuais mais adequados ao case',
            'Validei Mermaid para desenhar fluxos técnicos, mas a leitura ficou ruim para um contexto de portfólio executivo. O ajuste foi preparar o conteúdo para imagens amplas e mais orientadas a compreensão rápida.',
            'frontend',
            TIMESTAMP '2026-04-03 16:10:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-03 16:10:00',
            TIMESTAMP '2026-04-03 16:10:00'
        ),
        (
            'manual-journal-20260403-02',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Padronizei a narrativa dos projetos para vender valor sem inflar escopo',
            'Reescrevi os estudos de caso com foco em contexto, decisão técnica, risco e impacto percebido. A meta foi comunicar mais valor para negócio e liderança sem inventar entregas ou números.',
            'engineering',
            TIMESTAMP '2026-04-03 11:00:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-03 11:00:00',
            TIMESTAMP '2026-04-03 11:00:00'
        ),
        (
            'manual-journal-20260402-01',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Modelei formação e experiência como narrativa de posicionamento',
            'Estruturei a seção Sobre para mostrar progressão entre negócio, sistemas, liderança e dados. Em vez de um currículo seco, a página passou a comunicar direção profissional e coerência de repertório.',
            'product',
            TIMESTAMP '2026-04-02 15:25:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-02 15:25:00',
            TIMESTAMP '2026-04-02 15:25:00'
        ),
        (
            'manual-journal-20260401-01',
            'diegosantos-ai/diego-santos-me',
            'https://github.com/diegosantos-ai/diego-santos-me',
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'Deixei o Learning in Public operacional com ingestão, fallback e publicação',
            'Corrigi a integração com GitHub, tratei campos obrigatórios, adicionei trigger manual e mantive fallback local quando o enriquecimento por LLM não estiver disponível. Com isso, a feature passou a ter caminho operacional completo para entrar em produção.',
            'backend',
            TIMESTAMP '2026-04-01 18:05:00',
            'PUBLISHED',
            FALSE,
            'editorial:manual',
            TIMESTAMP '2026-04-01 18:05:00',
            TIMESTAMP '2026-04-01 18:05:00'
        )
) AS seed (
    external_id,
    repository_name,
    repository_url,
    pull_request_number,
    pull_request_url,
    title,
    summary,
    technical_category,
    event_date,
    status,
    is_auto_published,
    raw_source_reference,
    processed_at,
    published_at
)
WHERE NOT EXISTS (
    SELECT 1
    FROM learning_events existing
    WHERE existing.external_id = seed.external_id
);
