-- Atualiza os seeds editoriais com a versão final dos textos sem alterar a migration V3 já aplicada.

INSERT INTO learning_events (
    external_id,
    repository_name,
    repository_url,
    pull_request_number,
    pull_request_url,
    title,
    summary,
    technical_category,
    event_date,
    status,
    is_auto_published,
    raw_source_reference,
    processed_at,
    published_at
)
VALUES
    (
        'manual-journal-20260405-01',
        'diegosantos-ai/nexo360-new',
        'https://github.com/diegosantos-ai/nexo360-new',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'Arquitetura modular so faz sentido quando reduz acoplamento de verdade',
        'No Nexo 360, aprendi que separar dominio, entrada e saida nao e so uma escolha estetica. Essa organizacao reduz impacto de mudanca, melhora testabilidade e facilita evoluir partes do sistema sem espalhar regra de negocio por toda a aplicacao.',
        'architecture',
        TIMESTAMP '2026-04-05 10:30:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-05 10:30:00',
        TIMESTAMP '2026-04-05 10:30:00'
    ),
    (
        'manual-journal-20260405-02',
        'diegosantos-ai/nexo360-new',
        'https://github.com/diegosantos-ai/nexo360-new',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'Multi-tenant exige contexto explicito, nao suposicao implicita',
        'Trabalhar com uma arquitetura multi-tenant reforcou uma licao importante: contexto de tenant precisa entrar no desenho do sistema desde o inicio. Quando isso nao fica explicito em contratos, persistencia e fluxo de execucao, o risco de inconsistencias cresce rapido.',
        'backend',
        TIMESTAMP '2026-04-05 09:15:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-05 09:15:00',
        TIMESTAMP '2026-04-05 09:15:00'
    ),
    (
        'manual-journal-20260404-01',
        'diegosantos-ai/dev-workspace',
        'https://github.com/diegosantos-ai/dev-workspace',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'Ambiente reproduzivel economiza mais tempo do que qualquer ajuste manual',
        'No DevOps Workspace, ficou claro que padronizar setup e automacao de ambiente reduz atrito operacional, acelera onboarding e evita o custo invisivel de cada maquina funcionar de um jeito. Reprodutibilidade nao e detalhe; e base para trabalhar com previsibilidade.',
        'devops',
        TIMESTAMP '2026-04-04 17:40:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-04 17:40:00',
        TIMESTAMP '2026-04-04 17:40:00'
    ),
    (
        'manual-journal-20260404-02',
        'diegosantos-ai/projeto-02-terraform-cloud',
        'https://github.com/diegosantos-ai/projeto-02-terraform-cloud',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'Infraestrutura como codigo comeca a gerar valor quando vira rotina segura',
        'No projeto de infraestrutura em AWS, o aprendizado principal foi que Terraform entrega muito mais valor quando deixa de ser experimento e passa a organizar ambiente com consistencia, versionamento e menor dependencia de acao manual. O ganho real esta na previsibilidade da operacao.',
        'infrastructure',
        TIMESTAMP '2026-04-04 14:20:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-04 14:20:00',
        TIMESTAMP '2026-04-04 14:20:00'
    ),
    (
        'manual-journal-20260403-01',
        'diegosantos-ai/chat-bot-pref',
        'https://github.com/diegosantos-ai/chat-bot-pref',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'IA em producao precisa de governanca antes de precisar de sofisticacao',
        'Com o Munio, aprendi que aplicar IA em contexto institucional nao e so integrar modelo e resposta. E garantir contexto correto, trilha de auditoria, validacao de entrada e saida e uma base observavel para operar com responsabilidade em ambientes mais sensiveis.',
        'ai-governance',
        TIMESTAMP '2026-04-03 16:10:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-03 16:10:00',
        TIMESTAMP '2026-04-03 16:10:00'
    ),
    (
        'manual-journal-20260403-02',
        'diegosantos-ai/chat-bot-pref',
        'https://github.com/diegosantos-ai/chat-bot-pref',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'RAG so melhora a resposta quando o contexto esta realmente sob controle',
        'Ao estruturar o fluxo de RAG no Munio, a principal licao foi que recuperacao de contexto nao resolve sozinha o problema da qualidade. Sem isolamento adequado, politica clara e contexto bem delimitado, o sistema continua vulneravel a respostas genericas ou inconsistentes.',
        'rag',
        TIMESTAMP '2026-04-03 11:00:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-03 11:00:00',
        TIMESTAMP '2026-04-03 11:00:00'
    ),
    (
        'manual-journal-20260402-01',
        'diegosantos-ai/projeto-03-observabilidade',
        'https://github.com/diegosantos-ai/projeto-03-observabilidade',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'Sem sinal operacional, troubleshooting vira tentativa e erro',
        'Na stack de observabilidade, reforcei uma aprendizagem central: logs, metricas e dashboards nao servem apenas para monitorar. Eles encurtam diagnostico, ajudam a localizar falhas com menos atrito e transformam operacao reativa em leitura mais clara do sistema.',
        'observability',
        TIMESTAMP '2026-04-02 15:25:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-02 15:25:00',
        TIMESTAMP '2026-04-02 15:25:00'
    ),
    (
        'manual-journal-20260401-01',
        'diegosantos-ai/diego-santos-me',
        'https://github.com/diegosantos-ai/diego-santos-me',
        NULL::INTEGER,
        NULL::VARCHAR(255),
        'Apresentar projeto bem tambem e uma competencia de engenharia',
        'Ao transformar o portfolio em aplicacao estruturada, com backend, conteudo versionado e casos mais bem narrados, aprendi que comunicar arquitetura, decisao tecnica e valor operacional faz parte do trabalho. Projeto bom mal explicado perde forca; projeto bem comunicado vira evidencia.',
        'engineering',
        TIMESTAMP '2026-04-01 18:05:00',
        'PUBLISHED',
        FALSE,
        'editorial:manual',
        TIMESTAMP '2026-04-01 18:05:00',
        TIMESTAMP '2026-04-01 18:05:00'
    )
ON CONFLICT (external_id) DO UPDATE
SET
    repository_name = EXCLUDED.repository_name,
    repository_url = EXCLUDED.repository_url,
    pull_request_number = EXCLUDED.pull_request_number,
    pull_request_url = EXCLUDED.pull_request_url,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    technical_category = EXCLUDED.technical_category,
    event_date = EXCLUDED.event_date,
    status = EXCLUDED.status,
    is_auto_published = EXCLUDED.is_auto_published,
    raw_source_reference = EXCLUDED.raw_source_reference,
    processed_at = EXCLUDED.processed_at,
    published_at = EXCLUDED.published_at,
    updated_at = NOW();
